language: csharp
solution: SmartIrc4net.sln

mono:
    - latest
    - 4.2.3
    - 4.0.0
    - 3.12.0
    - 3.8.0

addons:
    apt:
        packages:
        - autoconf
        - automake
        - make
        - libtool

script:
    - ./autogen.sh
    - xbuild /p:Configuration=Release SmartIrc4net.sln
    - make clean; make fetch-packages; make distcheck

notifications:
    irc:
        channels: "chat.freenode.net#smuxi-devel"
        skip_join: true
        template:
            - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
            - "Build details : %{build_url}"
